media:
  - name: images
    label: Images
    input: public/images
    output: /images
    categories: [ image ]

content:
  - name: blogs
    label: Blogs
    type: collection
    path: src/content/blog
    filename: '{primary}.md'
    view:
      fields: [ author, title, pubDate ]
    fields:
      - name: author
        label: Author
        type: string
      - name: title
        label: Title
        type: string
      - name: description
        label: Description
        type: string
      - name: pubDate
        label: Date
        type: date
        options:
          time: true
          format: yyyy-MM-dd'T'HH:mm:ss+07:00
      - name: cover
        label: Cover
        type: object
        fields:
          - name: image
            label: Image
            type: image
          - name: hiddenInList
            label: Hidden in List
            type: boolean
            default: true
      # - name: showToc
      #   label: "Table Of Content"
      #   type: boolean
      #   default: true
      # - name: tocopen
      #   label: "Table of Content Open (default: false)"
      #   type: boolean
      #   default: false
      # - name: comments
      #   label: "Comments"
      #   type: boolean
      #   default: false
      - name: tags
        label: Tags
        type: select
        options:
          creatable: true
          multiple: true
          values: [ linux, kubernetes, docker ]
      - name: body
        label: Body
        type: rich-text

